apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Name }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ .Values.name }}
          image: cicd-demo:latest
          imagePullPolicy: always
          env:
            - name: PORT
              value: {{.Values.ContainerPort}}
          ports:
            - containerPort: {{ .Values.ContainerPort }}
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.HealthProbesTimeout }}
            timeoutSeconds: 5
            failureThreshold: {{ .Values.HealthProbeLivenessFailureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.HealthProbesTimeout }}
          resources:
            requests:
              cpu: "{{ .Values.Master.Cpu }}"
              memory: "{{ .Values.Master.Memory }}"